// <auto-generated />
namespace SC_601_PA_G5_M.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class pa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pa));
        
        string IMigrationMetadata.Id
        {
            get { return "202504100118188_pa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
